### PR TITLE
Turned into SDK to work around bug1310082

### PR DESCRIPTION
**Pull request by Noitidart**
WebExtension content scripts no longer work on AMO -
https://bugzilla.mozilla.org/show_bug.cgi?id=1310082 - so I had to make
this an SDK content script. This addon is too useful! Can't live without
it!

### CODE REVIEW

**Comment by jvillalobos** [comment]
Thanks, but I can't upload an update to the WebExtension due to [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1283443). Feel free to use it yourself, of course. I plan to branch out the older frame script version, update it, and distribute it as unlisted for a while.

**Comment by Noitidart** [comment]
Oh shoot. No problem. Makes sense.

Unlisted is probably the way to go for all our AMO specific addons no? Like this is what we ask of other companies uploading addons which have use limited to just their contributors?

**Comment by jvillalobos** [comment]
That's a fair question, maybe it makes sense to use unlisted for add-ons that are only useful for admins and reviewers. As long as add-ons are testable we do accept stuff that has limited usage, though.

**Comment by Noitidart** [comment]
Ahh. I'll for sure make that adjustment to approve if it's testable. I always leaned the other way. But this way sounds better - less communication with the devs as an added bonus! haha

**Pull request closed without merging**
